name: SuperSpleef
main: me.BenLoe.SuperSpleef.Main
version: 1.0
description: >
             Super Spleef Plugin
commands:
  SS:
    description: Staff Command
  Leave:
    description: Leave                                      
                                        
